### ISSUE TITLE
Why does RemoteAddr return laddr in the net.go?

### ISSUE THREAD

**Issue by bus710** [tinygo-org/drivers#296]
Hi,

Just like the title, I wonder why the RemoteAddr function returns laddr instead of raddr.
https://github.com/tinygo-org/drivers/blob/1cbf1a6f3d2c9758bfe0063e8b55be77d1890c49/net/net.go#L189

<br/>

This is the partial code for the functions:
```go
// LocalAddr returns the local network address.
func (c *UDPSerialConn) LocalAddr() Addr {
	return c.laddr.opAddr()
}

// RemoteAddr returns the remote network address.
func (c *UDPSerialConn) RemoteAddr() Addr {
	return c.laddr.opAddr()
}
```

<br/>

So I tried returning raddr in the RemoteAddr function but it returned 0(nil) - I mean, in some of my use cases. 
I guess it is rooted from WifiNina (of my nano33 IoT)?, but still wonder if there was any consideration behind of this code.

**Comment by sago35** [comment]
Perhaps it's a simple mistake.
Do you have any thoughts on this? @deadprogram  @bgould

**Comment by deadprogram** [comment]
I think just an error.

**Comment by sago35** [comment]
This problem has been fixed in the following.

https://github.com/tinygo-org/drivers/commit/0565a15b173084fc471924fa743f587097b666b1
https://github.com/tinygo-org/drivers/commit/4b38841f7113df44fce85d23df62712a459a4229

And it has been released.
Thanks for the report. @bus710 

https://github.com/tinygo-org/drivers/releases/tag/v0.18.0

**Comment by bus710** [comment]
@sago35 @deadprogram 
Very appreciated.
